apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ofiw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ofiw
    app.kubernetes.io/part-of: mashas-app
  name: devfile-sample-ofiw
  namespace: marialeonova-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ofiw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ofiw
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:65c6947033beb02ee4b93745cbc895b5566bc06b66963c7b949464b60cfa2ed0
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
